name: ads-b_postgis
services:

  database:
    build: .
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: adsb
      OPENSKY_USER: ${OPENSKY_USER}
      OPENSKY_PASS: ${OPENSKY_PASS}
      RAPIDAPI_KEY: ${RAPIDAPI_KEY}
    ports:
      - 5432:5432

    restart: always
