services:
  database:
    build: .
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: opensky
      OPENSKY_USER: ${OPENSKY_USER}
      OPENSKY_PASS: ${OPENSKY_PASS}
    ports:
      - 54321:5432

